version: "3.8"
services:
  prod:
    container_name: ${CONTAINER_NAME}
    image: "portainer/portainer-ce:2.14.0"
    mem_limit: 4000m
    cpus: 4
    restart: always
    ports:
      - ${APP_PORT}:9000
    volumes:
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"

